### ISSUE TITLE
Installation / Documentation

### ISSUE THREAD

**Issue by coinGuyBri** [aquanetwork/aquachain#2]
Newbie question, but How do I install go? on MAC OSx? pip install?
To build with go, use `go get -v github.com/aquanetwork/aquachain/cmd/aquachain`
@aerth

**Comment by aerth** [comment]
The golang website is nuts https://golang.org/doc/install

**Comment by aerth** [comment]
Glad you said something though, there are lots of documentation that needs to happen. 

"How to install on each platform step-by-step" is a great place.

I'm going to open up the wiki and we can keep this thread going with other questions about installation / usage
