### ISSUE TITLE
miner performance

### ISSUE THREAD

**Issue by aerth** [aquanetwork/aquachain#27]
currently, there may be better performance if using X number of instances of the miner, with `-t 1` flag, where X is the number of threads to use.

### linux or mac
this script requires aquaminer be installed in $PATH, for example /usr/local/bin/aquaminer

requires numactl, `sudo apt-get install numactl`

https://hastebin.com/avivafijux.bash

### windows

```
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
start aquaminer.exe -F <pool> -t 1 -r 1s
```

**Comment by forexlegend** [comment]
Ok, "-t x" is for cores of cpu. But what is "-r 1s" ???

**Comment by aerth** [comment]
@forexlegend `-r` flag is for refresh rate, like 1s or 3s or 5s

this miner is outdated and made obsolete by [aquacppminer](https://bitbucket.org/cryptogone/aquacppminer/)

Grab it here: https://bitbucket.org/cryptogone/aquacppminer/downloads

**Comment by aerth** [comment]
updated wiki: https://github.com/aquanetwork/aquachain/wiki/Mining
